name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Command tests"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
                shell:
                - "bash"
                include:
                -
                    os: "ubuntu-latest"
                    shell: "dash"
                -
                    os: "macos-latest"
                    shell: "zsh"
            fail-fast: false
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Display zsh version"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                echo "Name: ${ZSH_NAME} Version: ${ZSH_VERSION}"
        -
            name: "Run tests"
            if: "${{ matrix.shell == 'bash' }}"
            shell: "bash"
            run: |
                pwd
                find .
                . ./run_test.sh
        -
            name: "Run tests"
            if: "${{ matrix.shell == 'dash' }}"
            shell: "dash {0}"
            run: |
                pwd
                find .
                . ./run_test.sh
        -
            name: "Run tests"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                pwd
                find .
                . ./run_test.sh
