name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Command tests"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
                shell:
                - "bash"
                include:
                -
                    os: "ubuntu-latest"
                    shell: "dash"
                -
                    os: "macos-latest"
                    shell: "zsh"
            fail-fast: false
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Run tests with Bash"
            if: "${{ matrix.shell == 'bash' }}"
            shell: "bash --noprofile --norc -eo pipefail {0}"
            run: |
                pwd
                . ./run_test.sh
        -
            name: "Run tests with POSIX Bash"
            if: "${{ matrix.shell == 'bash' }}"
            shell: "bash --posix --noprofile --norc -eo pipefail {0}"
            run: |
                pwd
                . ./run_test.sh
        -
            name: "Run tests with Dash"
            if: "${{ matrix.shell == 'dash' }}"
            shell: "dash -e {0}"
            run: |
                pwd
                . ./run_test.sh
        -
            name: "Run tests with Zsh"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                pwd
                . ./run_test.sh
