name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Stream editor"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
            fail-fast: false
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Display zsh version"
            if: "${{ matrix.os == 'macos-latest' }}"
            shell: "zsh {0}"
            run: |
                echo "Name: ${ZSH_NAME} Version: ${ZSH_VERSION}"
        -
            name: "Display sed version"
            shell: "bash"
            run: |
                stat "$(which sed)"
        -
            name: "Run one or more occurrences test"
            if: "${{ matrix.os == 'ubuntu-latest' }}"
            shell: "bash"
            run: |
                test "$(echo "aLLma" | sed -E -e 's#(L+)#[\1]#')" = "a[LL]ma"
        -
            name: "Run one or more occurrences test"
            if: "${{ matrix.os == 'macos-latest' }}"
            shell: "zsh {0}"
            run: |
                test "$(echo "aLLma" | sed -E -e 's#(L+)#[\1]#')" = "a[LL]ma"
        -
            name: "Run one or more occurrences test"
            if: "${{ matrix.os == 'windows-latest' }}"
            shell: "bash"
            run: |
                test "$(echo "aLLma" | sed -E -e 's#(L+)#[\1]#')" = "a[LL]ma"
