name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Stream editor"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
                shell:
                - "bash"
                include:
                -
                    os: "macos-latest"
                    shell: "zsh"
            fail-fast: false
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Display zsh version"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                echo "Name: ${ZSH_NAME} Version: ${ZSH_VERSION}"
        -
            name: "Run tests ${{ matrix.shell == 'zsh' && 'zsh {0}' || 'bash' }}"
            shell: "bash"
            run: |
                run_test() {
                    TEST_NAME="$1"
                    TEST_COMMAND="$(cat "$1/command")"
                    TEST_OUTPUT="$(cat "$1/output")"
                    test "$(eval "${TEST_COMMAND}")" = "${TEST_OUTPUT}"
                }
                export -f run_test
                find ./ -mindepth 1 -maxdepth 1 -type d -exec run_test "{}" ";"
