name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Stream editor"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
                shell:
                - "bash"
                include:
                -
                    os: "macos-latest"
                    shell: "zsh"
            fail-fast: false
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Display zsh version"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                echo "Name: ${ZSH_NAME} Version: ${ZSH_VERSION}"
        -
            name: "Run one or more occurrences test"
            if: "${{ matrix.shell == 'zsh' }}"
            shell: "zsh {0}"
            run: |
                test "$(echo "aLLma" | sed -E -e 's#(L+)#[\1]#')" = "a[LL]ma"
        -
            name: "Run one or more occurrences test"
            if: "${{ matrix.shell == 'bash' }}"
            shell: "bash"
            run: |
                test "$(echo "aLLma" | sed -E -e 's#(L+)#[\1]#')" = "a[LL]ma"
