name: "Cross-platform"

on:
    push: null

jobs:
    sed:
        name: "Stream editor"
        strategy:
            matrix:
                os:
                - "ubuntu-latest"
                - "macos-latest"
                - "windows-latest"
        runs-on: "${{ matrix.os }}"
        steps:
        -
            name: "Install zsh"
            if: "${{ matrix.os == 'ubuntu-latest' }}"
            run: |
                sudo apt-get update
                sudo apt-get install -q zsh
        -
            name: "Install zsh"
            if: "${{ matrix.os == 'windows-latest' }}"
            run: |
                choco install zsh
        -
            name: "On zsh"
            shell: "zsh {0}"
            run: |
                echo "Name: ${ZSH_NAME} Version: ${ZSH_VERSION}"
                which -a sed
        -
            name: "Display sed version"
            if: "${{ matrix.os == 'macos-latest' }}"
            run: |
                pkgutil --file-info /usr/bin/sed
